"""
Phase 11: FastAPI backend (SRS section 16).

Thin REST wrapper over the Phase 10 agent tools -- every endpoint here returns
only facts already produced by phases 1-4/6 (see src/agent/tools.py). No
PostgreSQL/PostGIS yet: there's no real geographic data to store (Phase 7 is
blocked on Odisha district data), so this reads straight from the processed
CSVs, which is honest about how little state there currently is to persist.

Run: uvicorn backend.main:app --reload --port 8000   (from the project root)
"""

import os
import json
import sys
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.agent import tools as agent_tools
from src.agent import agent as agent_module
from src.db.db import connect_db, disconnect_db
from src.db import crud as db_crud
from src.db import cache_service
from src.retraining import retrain_pipeline

app = FastAPI(
    title="IDMAP-Cyclone API",
    description="Odisha cyclone intelligence backend with Neon DB & Prisma ORM persistence.",
    version="0.2.0",
)

@app.on_event("startup")
async def startup_event():
    try:
        await connect_db()
    except Exception as e:
        print(f"Warning: Neon DB connection on startup failed: {e}")


@app.on_event("shutdown")
async def shutdown_event():
    try:
        await disconnect_db()
    except Exception as e:
        print(f"Warning: Neon DB disconnect on shutdown failed: {e}")

cors_env = os.getenv("CORS_ORIGINS", "")
parsed_origins = [o.strip() for o in cors_env.split(",") if o.strip() and o.strip() != "*"]

default_origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "https://idmapfrontend.vercel.app",
]
allowed_origins = list(set(default_origins + parsed_origins))

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_origin_regex=r"https://.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# serves the actual cleaned satellite crops (data/processed/insat3d/<modality>/
# <split>/<base_id>/<filename>) so the dashboard can show real imagery, not just
# numbers, next to the anomaly scores and event details.
PROCESSED_INSAT3D = ROOT / "data" / "processed" / "insat3d"
if PROCESSED_INSAT3D.exists():
    app.mount("/static/insat3d", StaticFiles(directory=str(PROCESSED_INSAT3D)), name="insat3d-images")

# serves the evaluation report images (training curves, embedding-space plot)
# generated by src/cv_models/pretrain_tcir_backbone.py and
# src/layer2/anomaly_autoencoder/train_autoencoder.py
REPORTS_DIR = ROOT / "reports"
if REPORTS_DIR.exists():
    app.mount("/static/reports", StaticFiles(directory=str(REPORTS_DIR)), name="reports")


class AskRequest(BaseModel):
    question: str
    history: list[dict] = []


class EventPredictRequest(BaseModel):
    base_id: int


class RetrieveRequest(BaseModel):
    query: str
    top_k: int = 4


class AdvisoryRequest(BaseModel):
    base_id: int
    task: str = "advisory"


class WhatIfRequest(BaseModel):
    base_id: int
    delta_wind_speed_kt: float = 0.0
    new_coastal_distance_km: Optional[float] = None


class FeedbackRequest(BaseModel):
    advisory_id: str
    rating: int
    is_helpful: bool = True
    is_verified: bool = False
    corrections: Optional[str] = None


@app.get("/api/status")
def get_status():
    return agent_tools.get_project_status()


@app.get("/api/events")
def get_events(split: Optional[str] = None):
    return agent_tools.list_events(split=split)


@app.get("/api/events/{base_id}")
def get_event(base_id: int):
    result = agent_tools.get_event_summary(base_id)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.get("/api/anomalies")
def get_anomalies(top_n: int = 10, only_flagged: bool = True):
    return agent_tools.list_anomalies(top_n=top_n, only_flagged=only_flagged)


@app.post("/api/predict")
async def predict_event(req: EventPredictRequest):
    """Phase 3/4 CV Model Prediction & Anomaly score endpoint with Neon DB logging."""
    result = agent_tools.predict_event(req.base_id)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])

    # Log to Neon DB via Prisma asynchronously
    prediction_id = await db_crud.log_prediction(
        event_id=req.base_id,
        predicted_category=result.get("intensity_category", "Unknown"),
        severity=result.get("severity", "Low"),
        anomaly_error=result.get("anomaly_error", 0.0),
        vmax_proxy_kt=result.get("vmax_proxy_kt", 0.0),
        confidence=result.get("confidence", 1.0)
    )
    if prediction_id:
        result["db_prediction_id"] = prediction_id

    return result


@app.post("/api/forecast")
def forecast_event(req: EventPredictRequest):
    """Phase 5/7 Propagation & Warning Forecast endpoint."""
    result = agent_tools.predict_event(req.base_id)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return {
        "event_id": req.base_id,
        "intensity_category": result.get("intensity_category"),
        "severity": result.get("severity"),
        "vmax_proxy_kt": result.get("vmax_proxy_kt"),
        "warning_stage": "Cyclone Alert" if result.get("severity") in ["High", "Extreme"] else "Pre-Cyclone Watch"
    }


class LiveExplainRequest(BaseModel):
    wind_speed_kt: float = 65.0
    coastal_distance_km: float = 85.0
    district_population: float = 1250000.0
    pressure_hpa: float = 998.0
    anomaly_error: float = 0.08


@app.get("/api/explain/{base_id}")
def explain_event(base_id: int):
    """Phase 8 SHAP Explainability & feature importance attribution endpoint."""
    result = agent_tools.explain_risk_prediction(base_id)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.post("/api/explain/live")
def explain_live(req: LiveExplainRequest):
    """Phase 8 Live/Forecast SHAP Explainability feature attribution endpoint."""
    return agent_tools.explain_live_risk_prediction(
        wind_speed_kt=req.wind_speed_kt,
        coastal_distance_km=req.coastal_distance_km,
        district_population=req.district_population,
        pressure_hpa=req.pressure_hpa,
        anomaly_error=req.anomaly_error
    )



@app.post("/api/whatif")
def whatif_simulation(req: WhatIfRequest):
    """Phase 9 Interactive What-if Scenario simulation endpoint."""
    result = agent_tools.simulate_whatif_scenario(
        base_id=req.base_id,
        delta_wind_speed_kt=req.delta_wind_speed_kt,
        new_coastal_distance_km=req.new_coastal_distance_km
    )
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.get("/api/resources")
def get_resources(district: Optional[str] = None, severity: str = "High"):
    """Phase 9 Emergency resource planning & shelter allocation endpoint."""
    result = agent_tools.get_resource_plan(district_name=district, severity_level=severity)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


from fastapi import UploadFile, File

@app.post("/api/analyze-image")
async def analyze_image(file: UploadFile = File(...)):
    """Live Satellite Image Upload Analysis: extracts CNN features, detects anomalies, scores risk, and generates advisory."""
    from src.cv_models.analyze_image import analyze_uploaded_image
    contents = await file.read()
    result = analyze_uploaded_image(contents)
    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])
    return result


@app.get("/api/live/weather")
async def get_live_weather(refresh: bool = False):
    """Live Weather Ingestion with automatic Neon DB persistence & zero-blank caching."""
    return await cache_service.get_or_refresh_live_weather(force_refresh=refresh)


@app.get("/api/live/satellite")
def get_live_satellite():
    """Live Satellite Feed Metadata & Tile URLs via NASA GIBS / MOSDAC."""
    return agent_tools.get_live_satellite_feed()


@app.post("/api/analyze-live-satellite")
def analyze_live_satellite():
    """Fetches active NASA GIBS live satellite snapshot and runs TCIR + Autoencoder + XGBoost analysis."""
    from src.ingestion import live_satellite
    from src.cv_models import analyze_image
    import urllib.request

    feed = live_satellite.get_live_satellite_feed()
    tile_url = feed.get("nasa_gibs", {}).get("tile_snapshot_url")
    if not tile_url:
        raise HTTPException(status_code=500, detail="Failed to fetch live NASA GIBS satellite tile URL")

    try:
        req = urllib.request.Request(tile_url, headers={"User-Agent": "IDMAP-Ingest/1.0"})
        with urllib.request.urlopen(req, timeout=5) as resp:
            image_bytes = resp.read()
        res = analyze_image.analyze_uploaded_image(image_bytes)
        res["source_url"] = tile_url
        res["pass_date"] = feed.get("nasa_gibs", {}).get("date")
        return res
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Live satellite ingestion error: {str(e)}")


@app.post("/api/live/advisory")
def generate_live_advisory():
    """Real-time evidence-grounded AI advisory fusing live Open-Meteo readings with RAG retrieval."""
    return agent_tools.generate_live_advisory()


@app.post("/api/unified-live-survey")
async def get_unified_live_survey(refresh: bool = False):
    """Fuses all 5 AI/ML models into a single live Odisha disaster survey with automatic Neon DB caching."""
    return await cache_service.get_or_refresh_unified_survey(force_refresh=refresh)




@app.post("/api/retrieve")
def retrieve_knowledge(req: RetrieveRequest):
    """Phase 10 RAG Semantic Vector Retrieval endpoint."""
    chunks = agent_tools.retrieve_knowledge(req.query, top_k=req.top_k)
    return {"query": req.query, "results": chunks}


@app.post("/api/advisory")
async def generate_advisory(req: AdvisoryRequest):
    """Phase 10 Fused Multimodal CV + RAG Evidence-Grounded Advisory Report endpoint with Neon DB logging."""
    result = agent_tools.generate_advisory(req.base_id, task=req.task)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])

    # Persist advisory to Neon DB
    advisory_id = await db_crud.log_agent_advisory(
        event_id=req.base_id,
        prompt=f"Generate advisory report for base_id={req.base_id}, task={req.task}",
        advisory_text=result.get("advisory_markdown", ""),
        citations=result.get("citations", [])
    )
    if advisory_id:
        result["db_advisory_id"] = advisory_id

    return result


@app.post("/api/feedback")
async def submit_feedback(req: FeedbackRequest):
    """Submits human-in-the-loop expert rating and corrections for an AI advisory."""
    feedback_id = await db_crud.log_human_feedback(
        advisory_id=req.advisory_id,
        rating=req.rating,
        is_helpful=req.is_helpful,
        is_verified=req.is_verified,
        corrections=req.corrections
    )
    if not feedback_id:
        raise HTTPException(status_code=500, detail="Failed to persist feedback record to Neon DB.")
    return {"status": "success", "feedback_id": feedback_id}


@app.get("/api/history/advisories")
async def get_advisory_history(limit: int = 20):
    """Retrieves stored historical advisories along with human feedback from Neon DB."""
    advisories = await db_crud.fetch_advisories_with_feedback(limit=limit)
    return {"count": len(advisories), "advisories": advisories}


@app.post("/api/retrain/run")
async def run_retraining():
    """Triggers the automated retraining & AI dataset export pipeline."""
    report = await retrain_pipeline.run_retraining_pipeline()
    return report


@app.get("/api/district-graph")
def get_district_graph(district: Optional[str] = None):
    """Phase 7: Odisha district adjacency graph and risk propagation endpoint."""
    result = agent_tools.get_district_graph(district=district)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.post("/api/forecast/short-range")
async def forecast_short_range(refresh: bool = False):
    """Phase 12: 48-Hour Short-Range Operational Cyclone Track & Landfall Forecast with Neon DB caching."""
    return await cache_service.get_or_refresh_short_range_forecast(force_refresh=refresh)


@app.get("/api/forecast/seasonal-60day")
async def forecast_seasonal_outlook(refresh: bool = False):
    """Phase 12: 60-Day (2-Month) Seasonal Cyclone Probability & Vulnerability Outlook with Neon DB caching."""
    return await cache_service.get_or_refresh_seasonal_outlook(force_refresh=refresh)


@app.post("/api/agent/ask")
def ask_agent(req: AskRequest):
    result = agent_module.ask(req.question, history=req.history)
    return {"question": req.question, **result}


@app.get("/api/evaluation")
def get_evaluation():
    """Phase 3/6 evaluation artifacts: backbone + anomaly-detector metrics, and
    which report images are actually available to render. All values are read
    fresh from disk (checkpoints/history), never hardcoded, so this reflects
    whatever the most recent training run actually produced."""
    import torch

    result = {"backbone": None, "autoencoder": None, "images": {}}

    backbone_ckpt = ROOT / "src" / "cv_models" / "checkpoints" / "tcir_backbone.pt"
    if backbone_ckpt.exists():
        ckpt = torch.load(backbone_ckpt, map_location="cpu", weights_only=False)
        result["backbone"] = {
            "n_train_images": ckpt.get("n_train_images"),
            "final_val_mae_kt": ckpt.get("final_val_mae_kt"),
            "final_val_r2": ckpt.get("final_val_r2"),
            "dead_dims": ckpt.get("dead_dims"),
            "embed_dim": ckpt.get("embed_dim"),
            "pretext_task": ckpt.get("pretext_task"),
        }

    ae_ckpt = ROOT / "src" / "layer2" / "anomaly_autoencoder" / "checkpoints" / "autoencoder.pt"
    if ae_ckpt.exists():
        ckpt = torch.load(ae_ckpt, map_location="cpu", weights_only=False)
        result["autoencoder"] = {
            "active_embed_dims": len(ckpt.get("active_embed_cols", [])),
            "anomaly_threshold": ckpt.get("anomaly_threshold"),
            "anomaly_percentile": ckpt.get("anomaly_percentile"),
        }

    history_path = REPORTS_DIR / "tcir_backbone_history.json"
    if history_path.exists():
        with open(history_path, encoding="utf-8") as f:
            result["training_history"] = json.load(f)

    for name in ["tcir_backbone_training_curves.png", "embedding_space.png"]:
        result["images"][name] = (REPORTS_DIR / name).exists()

    return result


@app.get("/api/health")
def health():
    return {"ok": True}
