"""
Phase 11: FastAPI backend (SRS section 16).

Thin REST wrapper over the Phase 10 agent tools -- every endpoint here returns
only facts already produced by phases 1-4/6 (see src/agent/tools.py). No
PostgreSQL/PostGIS yet: there's no real geographic data to store (Phase 7 is
blocked on Odisha district data), so this reads straight from the processed
CSVs, which is honest about how little state there currently is to persist.

Run: uvicorn backend.main:app --reload --port 8000   (from the project root)
"""

import json
import sys
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.agent import tools as agent_tools
from src.agent import agent as agent_module

app = FastAPI(
    title="IDMAP-Cyclone API",
    description="Odisha cyclone intelligence backend. See /api/status for what's "
                 "actually implemented vs. still blocked on missing data.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# serves the actual cleaned satellite crops (data/processed/insat3d/<modality>/
# <split>/<base_id>/<filename>) so the dashboard can show real imagery, not just
# numbers, next to the anomaly scores and event details.
PROCESSED_INSAT3D = ROOT / "data" / "processed" / "insat3d"
if PROCESSED_INSAT3D.exists():
    app.mount("/static/insat3d", StaticFiles(directory=str(PROCESSED_INSAT3D)), name="insat3d-images")

# serves the evaluation report images (training curves, embedding-space plot)
# generated by src/cv_models/pretrain_tcir_backbone.py and
# src/layer2/anomaly_autoencoder/train_autoencoder.py
REPORTS_DIR = ROOT / "reports"
if REPORTS_DIR.exists():
    app.mount("/static/reports", StaticFiles(directory=str(REPORTS_DIR)), name="reports")


class AskRequest(BaseModel):
    question: str
    history: list[dict] = []


class EventPredictRequest(BaseModel):
    base_id: int


class RetrieveRequest(BaseModel):
    query: str
    top_k: int = 4


class AdvisoryRequest(BaseModel):
    base_id: int
    task: str = "advisory"


class WhatIfRequest(BaseModel):
    base_id: int
    delta_wind_speed_kt: float = 0.0
    new_coastal_distance_km: Optional[float] = None


@app.get("/api/status")
def get_status():
    return agent_tools.get_project_status()


@app.get("/api/events")
def get_events(split: Optional[str] = None):
    return agent_tools.list_events(split=split)


@app.get("/api/events/{base_id}")
def get_event(base_id: int):
    result = agent_tools.get_event_summary(base_id)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.get("/api/anomalies")
def get_anomalies(top_n: int = 10, only_flagged: bool = True):
    return agent_tools.list_anomalies(top_n=top_n, only_flagged=only_flagged)


@app.post("/api/predict")
def predict_event(req: EventPredictRequest):
    """Phase 3/4 CV Model Prediction & Anomaly score endpoint."""
    result = agent_tools.predict_event(req.base_id)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.post("/api/forecast")
def forecast_event(req: EventPredictRequest):
    """Phase 5/7 Propagation & Warning Forecast endpoint."""
    result = agent_tools.predict_event(req.base_id)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return {
        "event_id": req.base_id,
        "intensity_category": result.get("intensity_category"),
        "severity": result.get("severity"),
        "vmax_proxy_kt": result.get("vmax_proxy_kt"),
        "warning_stage": "Cyclone Alert" if result.get("severity") in ["High", "Extreme"] else "Pre-Cyclone Watch"
    }


class LiveExplainRequest(BaseModel):
    wind_speed_kt: float = 65.0
    coastal_distance_km: float = 85.0
    district_population: float = 1250000.0
    pressure_hpa: float = 998.0
    anomaly_error: float = 0.08


@app.get("/api/explain/{base_id}")
def explain_event(base_id: int):
    """Phase 8 SHAP Explainability & feature importance attribution endpoint."""
    result = agent_tools.explain_risk_prediction(base_id)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.post("/api/explain/live")
def explain_live(req: LiveExplainRequest):
    """Phase 8 Live/Forecast SHAP Explainability feature attribution endpoint."""
    return agent_tools.explain_live_risk_prediction(
        wind_speed_kt=req.wind_speed_kt,
        coastal_distance_km=req.coastal_distance_km,
        district_population=req.district_population,
        pressure_hpa=req.pressure_hpa,
        anomaly_error=req.anomaly_error
    )



@app.post("/api/whatif")
def whatif_simulation(req: WhatIfRequest):
    """Phase 9 Interactive What-if Scenario simulation endpoint."""
    result = agent_tools.simulate_whatif_scenario(
        base_id=req.base_id,
        delta_wind_speed_kt=req.delta_wind_speed_kt,
        new_coastal_distance_km=req.new_coastal_distance_km
    )
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.get("/api/resources")
def get_resources(district: Optional[str] = None, severity: str = "High"):
    """Phase 9 Emergency resource planning & shelter allocation endpoint."""
    result = agent_tools.get_resource_plan(district_name=district, severity_level=severity)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


from fastapi import UploadFile, File

@app.post("/api/analyze-image")
async def analyze_image(file: UploadFile = File(...)):
    """Live Satellite Image Upload Analysis: extracts CNN features, detects anomalies, scores risk, and generates advisory."""
    from src.cv_models.analyze_image import analyze_uploaded_image
    contents = await file.read()
    result = analyze_uploaded_image(contents)
    if "error" in result:
        raise HTTPException(status_code=400, detail=result["error"])
    return result


@app.get("/api/live/weather")
def get_live_weather():
    """Live Weather Ingestion via Open-Meteo API for 6 Odisha coastal/district stations."""
    return agent_tools.get_live_weather_feed()


@app.get("/api/live/satellite")
def get_live_satellite():
    """Live Satellite Feed Metadata & Tile URLs via NASA GIBS / MOSDAC."""
    return agent_tools.get_live_satellite_feed()


@app.post("/api/analyze-live-satellite")
def analyze_live_satellite():
    """Fetches active NASA GIBS live satellite snapshot and runs TCIR + Autoencoder + XGBoost analysis."""
    from src.ingestion import live_satellite
    from src.cv_models import analyze_image
    import urllib.request

    feed = live_satellite.get_live_satellite_feed()
    tile_url = feed.get("nasa_gibs", {}).get("tile_snapshot_url")
    if not tile_url:
        raise HTTPException(status_code=500, detail="Failed to fetch live NASA GIBS satellite tile URL")

    try:
        req = urllib.request.Request(tile_url, headers={"User-Agent": "IDMAP-Ingest/1.0"})
        with urllib.request.urlopen(req, timeout=5) as resp:
            image_bytes = resp.read()
        res = analyze_image.analyze_uploaded_image(image_bytes)
        res["source_url"] = tile_url
        res["pass_date"] = feed.get("nasa_gibs", {}).get("date")
        return res
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Live satellite ingestion error: {str(e)}")


@app.post("/api/live/advisory")
def generate_live_advisory():
    """Real-time evidence-grounded AI advisory fusing live Open-Meteo readings with RAG retrieval."""
    return agent_tools.generate_live_advisory()


@app.post("/api/unified-live-survey")
def get_unified_live_survey():
    """Fuses all 5 AI/ML models into a single live Odisha disaster survey."""
    from src.agent import unified_survey
    return unified_survey.generate_unified_live_survey()




@app.post("/api/retrieve")
def retrieve_knowledge(req: RetrieveRequest):
    """Phase 10 RAG Semantic Vector Retrieval endpoint."""
    chunks = agent_tools.retrieve_knowledge(req.query, top_k=req.top_k)
    return {"query": req.query, "results": chunks}


@app.post("/api/advisory")
def generate_advisory(req: AdvisoryRequest):
    """Phase 10 Fused Multimodal CV + RAG Evidence-Grounded Advisory Report endpoint."""
    result = agent_tools.generate_advisory(req.base_id, task=req.task)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.get("/api/district-graph")
def get_district_graph(district: Optional[str] = None):
    """Phase 7: Odisha district adjacency graph and risk propagation endpoint."""
    result = agent_tools.get_district_graph(district=district)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.post("/api/agent/ask")
def ask_agent(req: AskRequest):
    result = agent_module.ask(req.question, history=req.history)
    return {"question": req.question, **result}


@app.get("/api/evaluation")
def get_evaluation():
    """Phase 3/6 evaluation artifacts: backbone + anomaly-detector metrics, and
    which report images are actually available to render. All values are read
    fresh from disk (checkpoints/history), never hardcoded, so this reflects
    whatever the most recent training run actually produced."""
    import torch

    result = {"backbone": None, "autoencoder": None, "images": {}}

    backbone_ckpt = ROOT / "src" / "cv_models" / "checkpoints" / "tcir_backbone.pt"
    if backbone_ckpt.exists():
        ckpt = torch.load(backbone_ckpt, map_location="cpu", weights_only=False)
        result["backbone"] = {
            "n_train_images": ckpt.get("n_train_images"),
            "final_val_mae_kt": ckpt.get("final_val_mae_kt"),
            "final_val_r2": ckpt.get("final_val_r2"),
            "dead_dims": ckpt.get("dead_dims"),
            "embed_dim": ckpt.get("embed_dim"),
            "pretext_task": ckpt.get("pretext_task"),
        }

    ae_ckpt = ROOT / "src" / "layer2" / "anomaly_autoencoder" / "checkpoints" / "autoencoder.pt"
    if ae_ckpt.exists():
        ckpt = torch.load(ae_ckpt, map_location="cpu", weights_only=False)
        result["autoencoder"] = {
            "active_embed_dims": len(ckpt.get("active_embed_cols", [])),
            "anomaly_threshold": ckpt.get("anomaly_threshold"),
            "anomaly_percentile": ckpt.get("anomaly_percentile"),
        }

    history_path = REPORTS_DIR / "tcir_backbone_history.json"
    if history_path.exists():
        with open(history_path, encoding="utf-8") as f:
            result["training_history"] = json.load(f)

    for name in ["tcir_backbone_training_curves.png", "embedding_space.png"]:
        result["images"][name] = (REPORTS_DIR / name).exists()

    return result


@app.get("/api/health")
def health():
    return {"ok": True}
